import { PlannerForm } from './types';

export const samplePlan: PlannerForm = {
  planName: 'Quarterly workspace',
  income: {
    payFrequency: 'biweekly',
    firstPaycheckAmount: 2700,
    secondPaycheckAmount: 2700,
    extraIncome: 250,
    windowCutoffDay: 15,
  },
  spending: {
    firstWindowPersonalSpend: 450,
    secondWindowPersonalSpend: 450,
  },
  splitBills: [
    {
      id: 'bill-rent',
      name: 'Rent',
      kind: 'rent',
      category: 'Housing',
      dueDay: 1,
      totalAmount: 1800,
      firstWindowAmount: 1000,
      secondWindowAmount: 800,
      notes: 'Reserve the second part by the 15th.',
    },
    {
      id: 'bill-phone',
      name: 'Phone',
      kind: 'phone',
      category: 'Utilities',
      dueDay: 12,
      totalAmount: 200,
      firstWindowAmount: 100,
      secondWindowAmount: 100,
      notes: '',
    },
    {
      id: 'bill-power',
      name: 'Power',
      kind: 'utility',
      category: 'Utilities',
      dueDay: 18,
      totalAmount: 260,
      firstWindowAmount: 130,
      secondWindowAmount: 130,
      notes: '',
    },
    {
      id: 'bill-transport',
      name: 'Transportation',
      kind: 'transportation',
      category: 'Transportation',
      dueDay: null,
      totalAmount: 100,
      firstWindowAmount: 50,
      secondWindowAmount: 50,
      notes: 'Flexible allocation with no fixed due date.',
    },
  ],
  panels: {
    overview: {
      collapsed: false,
      layout: {
        x: 72,
        y: 84,
        width: 420,
        height: 220,
        zIndex: 1,
      },
    },
    summary: {
      collapsed: false,
      layout: {
        x: 520,
        y: 84,
        width: 420,
        height: 220,
        zIndex: 2,
      },
    },
    controls: {
      collapsed: false,
      layout: {
        x: 968,
        y: 84,
        width: 300,
        height: 220,
        zIndex: 3,
      },
    },
    signals: {
      collapsed: false,
      layout: {
        x: 1296,
        y: 84,
        width: 300,
        height: 220,
        zIndex: 4,
      },
    },
    splitLedger: {
      collapsed: false,
      layout: {
        x: 1180,
        y: 340,
        width: 560,
        height: 360,
        zIndex: 5,
      },
    },
    firstWindow: {
      collapsed: false,
      layout: {
        x: 1180,
        y: 728,
        width: 360,
        height: 300,
        zIndex: 6,
      },
    },
    secondWindow: {
      collapsed: false,
      layout: {
        x: 1568,
        y: 728,
        width: 360,
        height: 300,
        zIndex: 7,
      },
    },
  },
  debts: [
    {
      id: 'card-1',
      name: 'Chase Sapphire',
      kind: 'credit-card',
      sourceSplitBillId: null,
      balance: 4870,
      apr: 27.4,
      interestRate: 25.9,
      minimumPayment: 165,
      dueDay: 8,
      dueWindow: 'first',
      collapsed: false,
      layout: {
        x: 64,
        y: 340,
        width: 468,
        height: 336,
        zIndex: 8,
      },
    },
    {
      id: 'card-2',
      name: 'Capital One',
      kind: 'credit-card',
      sourceSplitBillId: null,
      balance: 2825,
      apr: 24.9,
      interestRate: 23.99,
      minimumPayment: 120,
      dueDay: 22,
      dueWindow: 'second',
      collapsed: false,
      layout: {
        x: 560,
        y: 340,
        width: 468,
        height: 336,
        zIndex: 9,
      },
    },
    {
      id: 'loan-1',
      name: 'Personal Loan',
      kind: 'personal-loan',
      sourceSplitBillId: null,
      balance: 7310,
      apr: 11.8,
      interestRate: 10.99,
      minimumPayment: 245,
      dueDay: 12,
      dueWindow: 'first',
      collapsed: false,
      layout: {
        x: 64,
        y: 704,
        width: 468,
        height: 336,
        zIndex: 10,
      },
    },
    {
      id: 'auto-1',
      name: 'Auto Note',
      kind: 'auto-loan',
      sourceSplitBillId: null,
      balance: 12840,
      apr: 6.1,
      interestRate: 5.79,
      minimumPayment: 360,
      dueDay: 26,
      dueWindow: 'second',
      collapsed: false,
      layout: {
        x: 560,
        y: 704,
        width: 468,
        height: 336,
        zIndex: 11,
      },
    },
  ],
};
